pipeline {
    agent any

    stages {
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network j-and-d
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=j-and-d-boot -Dsonar.projectName='j-and-d-boot'"
                    }
            }
        }

        stage('Docker Build') {
            steps {
                dir('j-and-d-back') {
                    sh 'docker build -t ajc/j-and-d:boot .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                    sh 'docker compose up -d --no-deps --build boot'
            }
        }
    }
}
